{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From <ipython-input-1-30845e518254>:9: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\n",
      "WARNING:tensorflow:From /Users/didi/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Please write your own downloading logic.\n",
      "WARNING:tensorflow:From /Users/didi/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Please use tf.data to implement this functionality.\n",
      "Extracting /tmp/data/train-images-idx3-ubyte.gz\n",
      "WARNING:tensorflow:From /Users/didi/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Please use tf.data to implement this functionality.\n",
      "Extracting /tmp/data/train-labels-idx1-ubyte.gz\n",
      "WARNING:tensorflow:From /Users/didi/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Please use tf.one_hot on tensors.\n",
      "Extracting /tmp/data/t10k-images-idx3-ubyte.gz\n",
      "Extracting /tmp/data/t10k-labels-idx1-ubyte.gz\n",
      "WARNING:tensorflow:From /Users/didi/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Please use alternatives such as official/mnist/dataset.py from tensorflow/models.\n"
     ]
    }
   ],
   "source": [
    "from __future__ import division, print_function, absolute_import\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "\n",
    "# Import MNIST data\n",
    "from tensorflow.examples.tutorials.mnist import input_data\n",
    "mnist = input_data.read_data_sets(\"/tmp/data/\", one_hot=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Training Params\n",
    "num_steps = 20000\n",
    "batch_size = 32\n",
    "\n",
    "# Network Params\n",
    "image_dim = 784 # 28*28 pixels * 1 channel\n",
    "gen_hidden_dim = 256\n",
    "disc_hidden_dim = 256\n",
    "noise_dim = 200 # Noise data points\n",
    "\n",
    "\n",
    "# Generator Network\n",
    "# Input: Noise, Output: Image\n",
    "def generator(x, reuse=False):\n",
    "    with tf.variable_scope('Generator', reuse=reuse):\n",
    "        # TensorFlow Layers automatically create variables and calculate their\n",
    "        # shape, based on the input.\n",
    "        x = tf.layers.dense(x, units=6 * 6 * 128)\n",
    "        x = tf.nn.tanh(x)\n",
    "        # Reshape to a 4-D array of images: (batch, height, width, channels)\n",
    "        # New shape: (batch, 6, 6, 128)\n",
    "        x = tf.reshape(x, shape=[-1, 6, 6, 128])\n",
    "        # Deconvolution, image shape: (batch, 14, 14, 64)\n",
    "        x = tf.layers.conv2d_transpose(x, 64, 4, strides=2)\n",
    "        # Deconvolution, image shape: (batch, 28, 28, 1)\n",
    "        x = tf.layers.conv2d_transpose(x, 1, 2, strides=2)\n",
    "        # Apply sigmoid to clip values between 0 and 1\n",
    "        x = tf.nn.sigmoid(x)\n",
    "        return x\n",
    "\n",
    "\n",
    "# Discriminator Network\n",
    "# Input: Image, Output: Prediction Real/Fake Image\n",
    "def discriminator(x, reuse=False):\n",
    "    with tf.variable_scope('Discriminator', reuse=reuse):\n",
    "        # Typical convolutional neural network to classify images.\n",
    "        x = tf.layers.conv2d(x, 64, 5)\n",
    "        x = tf.nn.tanh(x)\n",
    "        x = tf.layers.average_pooling2d(x, 2, 2)\n",
    "        x = tf.layers.conv2d(x, 128, 5)\n",
    "        x = tf.nn.tanh(x)\n",
    "        x = tf.layers.average_pooling2d(x, 2, 2)\n",
    "        x = tf.contrib.layers.flatten(x)\n",
    "        x = tf.layers.dense(x, 1024)\n",
    "        x = tf.nn.tanh(x)\n",
    "        # Output 2 classes: Real and Fake images\n",
    "        x = tf.layers.dense(x, 2)\n",
    "    return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From <ipython-input-2-603cea822f8f>:18: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use keras.layers.dense instead.\n",
      "WARNING:tensorflow:From /Users/didi/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1d59c4a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1d59c4a90>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1d59c4a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1d59c4a90>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:From <ipython-input-2-603cea822f8f>:24: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.keras.layers.Conv2DTranspose` instead.\n",
      "WARNING:tensorflow:Entity <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fe1dd3a4898>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fe1dd3a4898>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fe1dd3a4898>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fe1dd3a4898>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:From <ipython-input-2-603cea822f8f>:37: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.keras.layers.Conv2D` instead.\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a37b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a37b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:From <ipython-input-2-603cea822f8f>:39: average_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use keras.layers.AveragePooling2D instead.\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a37b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a37b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a37b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a37b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a37b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a37b8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:From /Users/didi/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1634: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use keras.layers.flatten instead.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1d59c4dd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1d59c4dd8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1d59c4dd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1d59c4dd8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a37b8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a37b8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a37b8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a37b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a37b8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a3e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a3e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a3e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a3e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a3e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a3e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a3e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a3e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a3e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a3e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a3e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1c22a3e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a3e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a3e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a3e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1c22a3e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1c2245f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1c2245f60>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1c2245f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1c2245f60>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a3e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a3e48>>: AttributeError: module 'gast' has no attribute 'Index'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a3e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c22a3e48>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c228c0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c228c0b8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c228c0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1c228c0b8>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1dd3a4898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1dd3a4898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1dd3a4898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1dd3a4898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1dd3a4898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fe1dd3a4898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1dd3a4898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x7fe1dd3a4898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1c2522780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1c2522780>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1c2522780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fe1c2522780>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1dd3a4898>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1dd3a4898>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1dd3a4898>>: AttributeError: module 'gast' has no attribute 'Index'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1dd3a4898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fe1dd3a4898>>: AttributeError: module 'gast' has no attribute 'Index'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Step 1: Generator Loss: 0.651424, Discriminator Loss: 0.713095\n",
      "Step 100: Generator Loss: 2.959169, Discriminator Loss: 0.451223\n",
      "Step 200: Generator Loss: 2.825483, Discriminator Loss: 0.186194\n",
      "Step 300: Generator Loss: 2.216427, Discriminator Loss: 0.459323\n",
      "Step 400: Generator Loss: 1.550671, Discriminator Loss: 0.539037\n",
      "Step 500: Generator Loss: 2.945562, Discriminator Loss: 0.188975\n",
      "Step 600: Generator Loss: 2.849946, Discriminator Loss: 0.211887\n",
      "Step 700: Generator Loss: 3.392182, Discriminator Loss: 0.183757\n",
      "Step 800: Generator Loss: 4.433300, Discriminator Loss: 0.186842\n",
      "Step 900: Generator Loss: 3.044041, Discriminator Loss: 0.141763\n",
      "Step 1000: Generator Loss: 3.821505, Discriminator Loss: 0.061441\n",
      "Step 1100: Generator Loss: 4.192065, Discriminator Loss: 0.142807\n",
      "Step 1200: Generator Loss: 4.130769, Discriminator Loss: 0.136424\n",
      "Step 1300: Generator Loss: 4.349351, Discriminator Loss: 0.088850\n",
      "Step 1400: Generator Loss: 4.565367, Discriminator Loss: 0.077817\n",
      "Step 1500: Generator Loss: 6.184347, Discriminator Loss: 0.074890\n",
      "Step 1600: Generator Loss: 4.577166, Discriminator Loss: 0.131667\n",
      "Step 1700: Generator Loss: 5.231580, Discriminator Loss: 0.255199\n",
      "Step 1800: Generator Loss: 4.286394, Discriminator Loss: 0.075804\n",
      "Step 1900: Generator Loss: 4.943582, Discriminator Loss: 0.072310\n",
      "Step 2000: Generator Loss: 7.525301, Discriminator Loss: 0.181625\n",
      "Step 2100: Generator Loss: 3.780496, Discriminator Loss: 0.076642\n",
      "Step 2200: Generator Loss: 4.982033, Discriminator Loss: 0.051564\n",
      "Step 2300: Generator Loss: 4.586709, Discriminator Loss: 0.089104\n",
      "Step 2400: Generator Loss: 4.752929, Discriminator Loss: 0.187637\n",
      "Step 2500: Generator Loss: 6.302032, Discriminator Loss: 0.089083\n",
      "Step 2600: Generator Loss: 6.309951, Discriminator Loss: 0.064461\n",
      "Step 2700: Generator Loss: 4.265791, Discriminator Loss: 0.064923\n",
      "Step 2800: Generator Loss: 6.129566, Discriminator Loss: 0.115808\n",
      "Step 2900: Generator Loss: 3.961375, Discriminator Loss: 0.082565\n",
      "Step 3000: Generator Loss: 7.035614, Discriminator Loss: 0.010049\n",
      "Step 3100: Generator Loss: 6.256183, Discriminator Loss: 0.022258\n",
      "Step 3200: Generator Loss: 4.847726, Discriminator Loss: 0.039437\n",
      "Step 3300: Generator Loss: 6.003361, Discriminator Loss: 0.068281\n",
      "Step 3400: Generator Loss: 5.782076, Discriminator Loss: 0.008390\n",
      "Step 3500: Generator Loss: 5.409564, Discriminator Loss: 0.168435\n",
      "Step 3600: Generator Loss: 4.448722, Discriminator Loss: 0.037708\n",
      "Step 3700: Generator Loss: 7.192139, Discriminator Loss: 0.008972\n",
      "Step 3800: Generator Loss: 6.270166, Discriminator Loss: 0.102477\n",
      "Step 3900: Generator Loss: 5.978486, Discriminator Loss: 0.052432\n",
      "Step 4000: Generator Loss: 5.890544, Discriminator Loss: 0.162781\n",
      "Step 4100: Generator Loss: 4.331239, Discriminator Loss: 0.040617\n",
      "Step 4200: Generator Loss: 5.949999, Discriminator Loss: 0.097358\n",
      "Step 4300: Generator Loss: 6.066223, Discriminator Loss: 0.163103\n",
      "Step 4400: Generator Loss: 4.693927, Discriminator Loss: 0.091843\n",
      "Step 4500: Generator Loss: 5.352235, Discriminator Loss: 0.023523\n",
      "Step 4600: Generator Loss: 6.432297, Discriminator Loss: 0.150453\n",
      "Step 4700: Generator Loss: 5.560987, Discriminator Loss: 0.050253\n",
      "Step 4800: Generator Loss: 4.770334, Discriminator Loss: 0.074512\n",
      "Step 4900: Generator Loss: 6.286059, Discriminator Loss: 0.127109\n",
      "Step 5000: Generator Loss: 5.728027, Discriminator Loss: 0.010259\n",
      "Step 5100: Generator Loss: 4.149532, Discriminator Loss: 0.042304\n",
      "Step 5200: Generator Loss: 3.467174, Discriminator Loss: 0.226300\n",
      "Step 5300: Generator Loss: 4.926167, Discriminator Loss: 0.059720\n",
      "Step 5400: Generator Loss: 4.168132, Discriminator Loss: 0.061828\n",
      "Step 5500: Generator Loss: 6.749673, Discriminator Loss: 0.044430\n",
      "Step 5600: Generator Loss: 5.519642, Discriminator Loss: 0.158429\n",
      "Step 5700: Generator Loss: 4.665912, Discriminator Loss: 0.183700\n",
      "Step 5800: Generator Loss: 4.629008, Discriminator Loss: 0.064549\n",
      "Step 5900: Generator Loss: 5.391356, Discriminator Loss: 0.021870\n",
      "Step 6000: Generator Loss: 3.974515, Discriminator Loss: 0.108903\n",
      "Step 6100: Generator Loss: 4.291204, Discriminator Loss: 0.182024\n",
      "Step 6200: Generator Loss: 4.410070, Discriminator Loss: 0.055540\n",
      "Step 6300: Generator Loss: 4.349064, Discriminator Loss: 0.099223\n",
      "Step 6400: Generator Loss: 5.081562, Discriminator Loss: 0.066996\n",
      "Step 6500: Generator Loss: 5.122930, Discriminator Loss: 0.099840\n",
      "Step 6600: Generator Loss: 1.993217, Discriminator Loss: 0.231096\n",
      "Step 6700: Generator Loss: 7.534420, Discriminator Loss: 0.117816\n",
      "Step 6800: Generator Loss: 3.415629, Discriminator Loss: 0.076048\n",
      "Step 6900: Generator Loss: 3.687920, Discriminator Loss: 0.103273\n",
      "Step 7000: Generator Loss: 4.385196, Discriminator Loss: 0.124241\n",
      "Step 7100: Generator Loss: 4.597970, Discriminator Loss: 0.050388\n",
      "Step 7200: Generator Loss: 5.156441, Discriminator Loss: 0.009493\n",
      "Step 7300: Generator Loss: 5.619066, Discriminator Loss: 0.024751\n",
      "Step 7400: Generator Loss: 3.319409, Discriminator Loss: 0.147792\n",
      "Step 7500: Generator Loss: 4.865544, Discriminator Loss: 0.246204\n",
      "Step 7600: Generator Loss: 4.319212, Discriminator Loss: 0.021423\n",
      "Step 7700: Generator Loss: 4.806592, Discriminator Loss: 0.162953\n",
      "Step 7800: Generator Loss: 3.969397, Discriminator Loss: 0.040387\n",
      "Step 7900: Generator Loss: 3.313713, Discriminator Loss: 0.098482\n",
      "Step 8000: Generator Loss: 5.035660, Discriminator Loss: 0.195951\n",
      "Step 8100: Generator Loss: 3.902432, Discriminator Loss: 0.058966\n",
      "Step 8200: Generator Loss: 4.348156, Discriminator Loss: 0.060795\n",
      "Step 8300: Generator Loss: 3.665701, Discriminator Loss: 0.045172\n",
      "Step 8400: Generator Loss: 4.229210, Discriminator Loss: 0.030920\n",
      "Step 8500: Generator Loss: 2.946675, Discriminator Loss: 0.092597\n",
      "Step 8600: Generator Loss: 4.298099, Discriminator Loss: 0.152029\n",
      "Step 8700: Generator Loss: 4.023558, Discriminator Loss: 0.038421\n",
      "Step 8800: Generator Loss: 5.402633, Discriminator Loss: 0.020970\n",
      "Step 8900: Generator Loss: 4.983440, Discriminator Loss: 0.108049\n",
      "Step 9000: Generator Loss: 6.098917, Discriminator Loss: 0.091608\n",
      "Step 9100: Generator Loss: 5.706020, Discriminator Loss: 0.073975\n",
      "Step 9200: Generator Loss: 6.145442, Discriminator Loss: 0.433265\n",
      "Step 9300: Generator Loss: 5.273024, Discriminator Loss: 0.109517\n",
      "Step 9400: Generator Loss: 3.775586, Discriminator Loss: 0.108014\n",
      "Step 9500: Generator Loss: 4.513432, Discriminator Loss: 0.023847\n",
      "Step 9600: Generator Loss: 3.988413, Discriminator Loss: 0.112176\n",
      "Step 9700: Generator Loss: 5.666192, Discriminator Loss: 0.051895\n",
      "Step 9800: Generator Loss: 4.838989, Discriminator Loss: 0.101025\n",
      "Step 9900: Generator Loss: 3.871034, Discriminator Loss: 0.101089\n",
      "Step 10000: Generator Loss: 3.218146, Discriminator Loss: 0.168432\n",
      "Step 10100: Generator Loss: 2.716325, Discriminator Loss: 0.232046\n",
      "Step 10200: Generator Loss: 3.451428, Discriminator Loss: 0.176092\n",
      "Step 10300: Generator Loss: 3.075576, Discriminator Loss: 0.147167\n",
      "Step 10400: Generator Loss: 4.937124, Discriminator Loss: 0.094208\n",
      "Step 10500: Generator Loss: 4.514955, Discriminator Loss: 0.128394\n",
      "Step 10600: Generator Loss: 2.947277, Discriminator Loss: 0.104480\n",
      "Step 10700: Generator Loss: 3.804507, Discriminator Loss: 0.041443\n",
      "Step 10800: Generator Loss: 3.292500, Discriminator Loss: 0.097570\n",
      "Step 10900: Generator Loss: 5.970593, Discriminator Loss: 0.076446\n",
      "Step 11000: Generator Loss: 3.440606, Discriminator Loss: 0.098490\n",
      "Step 11100: Generator Loss: 3.739675, Discriminator Loss: 0.084728\n",
      "Step 11200: Generator Loss: 3.839343, Discriminator Loss: 0.120586\n",
      "Step 11300: Generator Loss: 5.006063, Discriminator Loss: 0.125645\n",
      "Step 11400: Generator Loss: 3.989598, Discriminator Loss: 0.155027\n",
      "Step 11500: Generator Loss: 4.242995, Discriminator Loss: 0.179264\n",
      "Step 11600: Generator Loss: 3.314979, Discriminator Loss: 0.138004\n",
      "Step 11700: Generator Loss: 4.847676, Discriminator Loss: 0.105614\n",
      "Step 11800: Generator Loss: 3.677439, Discriminator Loss: 0.148631\n",
      "Step 11900: Generator Loss: 4.826647, Discriminator Loss: 0.093880\n",
      "Step 12000: Generator Loss: 4.689347, Discriminator Loss: 0.249910\n",
      "Step 12100: Generator Loss: 3.664052, Discriminator Loss: 0.102103\n",
      "Step 12200: Generator Loss: 6.665716, Discriminator Loss: 0.064459\n",
      "Step 12300: Generator Loss: 3.496277, Discriminator Loss: 0.159368\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Step 12400: Generator Loss: 5.042143, Discriminator Loss: 0.011581\n",
      "Step 12500: Generator Loss: 2.901745, Discriminator Loss: 0.084078\n",
      "Step 12600: Generator Loss: 5.068158, Discriminator Loss: 0.018624\n",
      "Step 12700: Generator Loss: 4.560118, Discriminator Loss: 0.090586\n",
      "Step 12800: Generator Loss: 4.837615, Discriminator Loss: 0.027640\n"
     ]
    }
   ],
   "source": [
    "# Build Networks\n",
    "# Network Inputs\n",
    "noise_input = tf.placeholder(tf.float32, shape=[None, noise_dim])\n",
    "real_image_input = tf.placeholder(tf.float32, shape=[None, 28, 28, 1])\n",
    "\n",
    "# Build Generator Network\n",
    "gen_sample = generator(noise_input)\n",
    "\n",
    "# Build 2 Discriminator Networks (one from real image input, one from generated samples)\n",
    "disc_real = discriminator(real_image_input)\n",
    "disc_fake = discriminator(gen_sample, reuse=True)\n",
    "disc_concat = tf.concat([disc_real, disc_fake], axis=0)\n",
    "\n",
    "# Build the stacked generator/discriminator\n",
    "stacked_gan = discriminator(gen_sample, reuse=True)\n",
    "\n",
    "# Build Targets (real or fake images)\n",
    "disc_target = tf.placeholder(tf.int32, shape=[None])\n",
    "gen_target = tf.placeholder(tf.int32, shape=[None])\n",
    "\n",
    "# Build Loss\n",
    "disc_loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(\n",
    "    logits=disc_concat, labels=disc_target))\n",
    "gen_loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(\n",
    "    logits=stacked_gan, labels=gen_target))\n",
    "\n",
    "# Build Optimizers\n",
    "optimizer_gen = tf.train.AdamOptimizer(learning_rate=0.001)\n",
    "optimizer_disc = tf.train.AdamOptimizer(learning_rate=0.001)\n",
    "\n",
    "# Training Variables for each optimizer\n",
    "# By default in TensorFlow, all variables are updated by each optimizer, so we\n",
    "# need to precise for each one of them the specific variables to update.\n",
    "# Generator Network Variables\n",
    "gen_vars = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, scope='Generator')\n",
    "# Discriminator Network Variables\n",
    "disc_vars = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, scope='Discriminator')\n",
    "\n",
    "# Create training operations\n",
    "train_gen = optimizer_gen.minimize(gen_loss, var_list=gen_vars)\n",
    "train_disc = optimizer_disc.minimize(disc_loss, var_list=disc_vars)\n",
    "\n",
    "# Initialize the variables (i.e. assign their default value)\n",
    "init = tf.global_variables_initializer()\n",
    "\n",
    "# Start training\n",
    "with tf.Session() as sess:\n",
    "\n",
    "    # Run the initializer\n",
    "    sess.run(init)\n",
    "\n",
    "    for i in range(1, num_steps+1):\n",
    "\n",
    "        # Prepare Input Data\n",
    "        # Get the next batch of MNIST data (only images are needed, not labels)\n",
    "        batch_x, _ = mnist.train.next_batch(batch_size)\n",
    "        batch_x = np.reshape(batch_x, newshape=[-1, 28, 28, 1])\n",
    "        # Generate noise to feed to the generator\n",
    "        z = np.random.uniform(-1., 1., size=[batch_size, noise_dim])\n",
    "\n",
    "        # Prepare Targets (Real image: 1, Fake image: 0)\n",
    "        # The first half of data fed to the discriminator are real images,\n",
    "        # the other half are fake images (coming from the generator).\n",
    "        batch_disc_y = np.concatenate(\n",
    "            [np.ones([batch_size]), np.zeros([batch_size])], axis=0)\n",
    "        # Generator tries to fool the discriminator, thus targets are 1.\n",
    "        batch_gen_y = np.ones([batch_size])\n",
    "\n",
    "        # Training\n",
    "        feed_dict = {real_image_input: batch_x, noise_input: z,\n",
    "                     disc_target: batch_disc_y, gen_target: batch_gen_y}\n",
    "        _, _, gl, dl = sess.run([train_gen, train_disc, gen_loss, disc_loss],\n",
    "                                feed_dict=feed_dict)\n",
    "        if i % 100 == 0 or i == 1:\n",
    "            print('Step %i: Generator Loss: %f, Discriminator Loss: %f' % (i, gl, dl))\n",
    "\n",
    "    # Generate images from noise, using the generator network.\n",
    "    f, a = plt.subplots(4, 10, figsize=(10, 4))\n",
    "    for i in range(10):\n",
    "        # Noise input.\n",
    "        z = np.random.uniform(-1., 1., size=[4, noise_dim])\n",
    "        g = sess.run(gen_sample, feed_dict={noise_input: z})\n",
    "        for j in range(4):\n",
    "            # Generate image from noise. Extend to 3 channels for matplot figure.\n",
    "            img = np.reshape(np.repeat(g[j][:, :, np.newaxis], 3, axis=2),\n",
    "                             newshape=(28, 28, 3))\n",
    "            a[j][i].imshow(img)\n",
    "\n",
    "    f.show()\n",
    "    plt.draw()\n",
    "    plt.waitforbuttonpress()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
